server:
  port: 8766

spring:
  application:
    name: Recieve-File-Service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smbms?serverTimezone=UTC
    username: root
    password: ok

eureka:
  client:
    service-url:
      defaultZone:  http://192.168.0.100:8761/eureka/
  instance:
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath:mappings/*.xml
  configuration:
    auto-mapping-behavior: full

logging:
  level:
    com.zb.recieve.dao: debug
